networks:
  laravel-network:
    driver: bridge
  payment-processor:
    external: true

services:
  nginx:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    container_name: laravel-nginx
    ports:
      - '9000:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app1
      - app2
      - redis
    networks:
      - laravel-network
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "15MB"

  app1:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    container_name: laravel-app1
    hostname: app1
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - laravel-network
      - payment-processor
    environment:
      - REDIS_ADDRESS=redis:6379
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "60MB"

  app2:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    container_name: laravel-app2
    hostname: app2
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - laravel-network
      - payment-processor
    environment:
      - REDIS_ADDRESS=redis:6379
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "60MB"
  redis:
    image: redis:7-alpine
    container_name: laravel-redis
    networks:
      - laravel-network
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "275MB"
  

  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
