networks:
  laravel-network:
    name: laravel-network
    driver: bridge
  payment-processor:
    external: true

services:
  server:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    container_name: laravel-server
    ports:
      - '9000:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
    networks:
      - laravel-network
  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    container_name: laravel-app
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - laravel-network
  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
    container_name: laravel-db
    ports:
      - "3309:3306"
    networks:
      - laravel-network
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
